media:
  input: public/images
  output: /images
content:
  - name: news
    label: Updates & Events
    type: collection
    path: src/content/news
    fields:
      - name: title
        label: Article Title
        type: string
        required: true
      - name: category
        label: Category
        type: select
        options:
          values:
            - Events
            - Street Action
            - Announcements
        required: true
      - name: date
        label: Date (Event Date or Publish Date)
        type: date
        required: true
      - name: location
        label: Location (Optional)
        type: string
      - name: featured_image
        label: Featured Image
        type: image
      - name: body
        label: Article Content
        type: rich-text
        required: true